"""Write results/numbers.tex: one \\newcommand per quantity the paper quotes."""

import os, csv, re

HERE = os.path.dirname(os.path.abspath(__file__))
R = os.path.join(HERE, "results")
out = []


def cmd(name, val):
    name = re.sub(r"[^A-Za-z]", "", name)
    out.append(f"\\newcommand{{\\{name}}}{{{val}}}")


def pm(v, e, nd=2):
    return f"{float(v):+.{nd}f}\\pm{float(e):.{nd}f}".replace("+", "")


for r in csv.DictReader(open(os.path.join(R, "headline.csv"))):
    k = r["code"].title().replace("Tng", "Tng") + r["sample"].title()
    cmd(f"aStar{k}", pm(r["a_star"], r["e_star"]))
    cmd(f"bHalo{k}", pm(r["b_halo"], r["e_halo"]))
    cmd(f"rHalo{k}", f"{float(r['r_halo_given_star']):+.2f}")
    cmd(f"rStar{k}", f"{float(r['r_star_given_halo']):+.2f}")
    cmd(f"N{k}", f"{int(r['N']):,}")
    cmd(f"haloAdds{k}", f"{float(r['halo_adds_pct']):.1f}")
    cmd(f"galaxyAdds{k}", f"{float(r['galaxy_adds_pct']):.1f}")
for r in csv.DictReader(open(os.path.join(R, "simba_variants.csv"))):
    if r["sample"] != "all":
        continue
    k = (
        r["run"]
        .replace("s50", "S")
        .replace("nofb", "Nofb")
        .replace("noagn", "Noagn")
        .replace("nojet", "Nojet")
        .replace("nox", "Nox")
    )
    k = "Full" if k == "S" else k
    cmd(f"bHaloVar{k}", pm(r["b_halo"], r["e_halo"]))
    cmd(f"aStarVar{k}", pm(r["a_star"], r["e_star"]))
    cmd(f"NVar{k}", f"{int(r['N']):,}")
for r in csv.DictReader(open(os.path.join(R, "forecast.csv"))):
    s = f"{float(r['sigma_h']):.1f}".replace(".", "p")
    cmd(f'forecastP{s}N{r["N"]}', f"{float(r['p_EAGLE_above_TNG_3sig']):.2f}")
open(os.path.join(R, "numbers.tex"), "w").write(
    "% generated by reanalysis/v3/make_numbers.py; do not edit\n" + "\n".join(out) + "\n"
)
print(len(out), "macros ->", os.path.join(R, "numbers.tex"))
